### ISSUE TITLE
PHPUnit Test Failure Due to Incompatible setUp() Declaration

### ISSUE THREAD

**Issue by rajandangi** [MURBASLMS/block_surveylinks#2]
Running the PHPUnit test suite `block_surveylinks_testsuite` results in a fatal error. The `setUp()` method in several test classes is not compatible with `PHPUnit\Framework\TestCase::setUp(): void`.

**The following files and lines are affected:**

1. `surveylinks/tests/block_surveylinks_test.php` 
2. `surveylinks/tests/edit_form_test.php` 
3. `surveylinks/tests/event/http_request_failed_test.php` 
4. `surveylinks/tests/explorance_api_test.php` 
5. `surveylinks/tests/privacy/provider_test.php` 
6. `surveylinks/tests/surveylink_model_test.php` 

**Environment**
- Moodle 4.1
- PHP: 7.4

**Comment by MURBASLMS** [comment]
work well, thanks
