### ISSUE TITLE
 Default exception handler: Exception - Call to a member function get_filename() on bool 

### ISSUE THREAD

**Issue by MURBASLMS** [MURBASLMS/block_surveylinks#4]
FYI i'm seeing a lot of this in mdl 401 php 7.4

[Thu Oct 03 07:23:56.338548 2024] [php7:notice] [pid 567073:tid 567073] [client 127.0.0.1:50394] Default exception handler: Exception - Call to a member function get_filename() on bool Debug: \nError code: generalexceptionmessage\n* line 52 of /blocks/surveylinks/lib.php: Error thrown\n* line 5282 of /lib/filelib.php: call to block_surveylinks_pluginfile()\n* line 44 of /pluginfile.php: call to file_pluginfile()\n, referer: https://moodleprod.murdoch.edu.au/course/view.php?id=25270
[Thu Oct 03 07:23:56.618720 2024] [php7:notice] [pid 580552:tid 580552] [client 127.0.0.1:50334] Default exception handler: Exception - Call to a member function get_filename() on bool Debug: \nError code: generalexceptionmessage\n* line 52 of /blocks/surveylinks/lib.php: Error thrown\n* line 5282 of /lib/filelib.php: call to block_surveylinks_pluginfile()\n* line 44 of /pluginfile.php: call to file_pluginfile()\n, referer: https://moodleprod.murdoch.edu.au/course/view.php?id=25241

**Comment by dmitriim** [comment]
Fixed
